name: publish

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - name: Generate pages
      run: |
        npm ci
        npm run generate
    - name: Deploy to GitHub Pages
      uses: comfuture/actions/ghpages@master
      env:
        BUILD_DIR: dist/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
